import { defineTheme } from "../build-tokens"
import {
  CHROME_DARK_DARK,
  CHROME_DARK_LIGHT,
  REF,
} from "../shared/pro-palette"

const BENTO_EXTRA_LIGHT = {
  "--gap": "16px",
  "--tile-padding": "24px",
  "--tile-padding-compact": "16px",
  "--section-gap": "32px",
  "--shadow-interactive": REF.shadowCardMd,
  "--duration-fast": "150ms",
  "--duration-normal": "200ms",
  "--ease-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "--space-4": "16px",
  ...CHROME_DARK_LIGHT,
}

const BENTO_EXTRA_DARK = {
  "--gap": "16px",
  "--tile-padding": "24px",
  "--tile-padding-compact": "16px",
  "--section-gap": "32px",
  "--shadow-interactive":
    "0 2px 4px rgba(0, 0, 0, 0.35), 0 12px 32px rgba(0, 0, 0, 0.45)",
  "--duration-fast": "150ms",
  "--duration-normal": "200ms",
  "--ease-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "--space-4": "16px",
  ...CHROME_DARK_DARK,
}

/** Dribbble bento dashboard — warm cream canvas, white tiles, dark chrome sidebar, violet accent. */
export const bento = defineTheme({
  name: "bento",
  label: "Bento Box",
  light: {
    palette: {
      canvas: REF.cream,
      canvasHover: REF.creamDeep,
      surface: REF.white,
      surfaceHover: REF.white,
      elevated: REF.white,
      field: REF.white,
      text: REF.ink,
      textMuted: REF.inkMuted,
      textSubtle: REF.inkSubtle,
      accent: REF.violetInteractive,
      accentHover: REF.violetInteractiveHover,
      accentFg: REF.violetDeep,
      onAccent: REF.white,
      danger: REF.danger,
      dangerHover: "#D44A3A",
      onDanger: REF.white,
      warning: REF.warning,
      info: REF.violetDeep,
      border: REF.borderHairline,
      borderStrong: REF.borderHairlineStrong,
      borderStyle: "soft",
      radius: REF.radiusLg,
      borderWidth: "1px",
      shadow: REF.shadowCard,
      shadowSm: "0 1px 2px rgba(0, 0, 0, 0.03), 0 4px 12px rgba(0, 0, 0, 0.04)",
      shadowMd: REF.shadowCardMd,
      shadowLg: REF.shadowCardLg,
      shadowPressed: "inset 0 1px 2px rgba(0, 0, 0, 0.06)",
      blur: "12px",
      glow: "0 0 0 4px rgba(157, 123, 255, 0.14)",
      focusRing: `3px solid ${REF.violet}`,
      focusRingOffset: "2px",
      highlight: "rgba(157, 123, 255, 0.10)",
      highlightHover: "rgba(157, 123, 255, 0.16)",
      tags: {
        purple: {
          bg: "#F0EBFF",
          bgHover: "#E4DAFF",
          text: "#5B3FD4",
          border: "rgba(157, 123, 255, 0.25)",
          icon: REF.violet,
        },
        green: {
          bg: REF.successMuted,
          bgHover: "#C8E8D8",
          text: "#2A6B4A",
          border: "rgba(61, 154, 106, 0.25)",
          icon: REF.success,
        },
        red: {
          bg: REF.dangerMuted,
          bgHover: "#FAD8D4",
          text: "#A83224",
          border: "rgba(232, 93, 76, 0.25)",
          icon: REF.danger,
        },
      },
    },
    extra: BENTO_EXTRA_LIGHT,
  },
  dark: {
    palette: {
      canvas: "#0C0C10",
      canvasHover: "#121218",
      surface: "#18181C",
      surfaceHover: "#1E1E24",
      elevated: "#222228",
      field: "#1A1A20",
      text: "#F4F4F5",
      textMuted: "#A1A1AA",
      textSubtle: "#71717A",
      accent: REF.violetInteractive,
      accentHover: REF.violetInteractiveHover,
      accentFg: "#C4B5FD",
      onAccent: REF.white,
      danger: "#F87171",
      border: "rgba(255, 255, 255, 0.08)",
      borderStrong: "rgba(255, 255, 255, 0.14)",
      borderStyle: "soft",
      radius: REF.radiusLg,
      borderWidth: "1px",
      shadow:
        "0 1px 2px rgba(0, 0, 0, 0.45), 0 10px 28px rgba(0, 0, 0, 0.55)",
      shadowSm:
        "0 1px 2px rgba(0, 0, 0, 0.35), 0 4px 12px rgba(0, 0, 0, 0.4)",
      shadowMd:
        "0 2px 4px rgba(0, 0, 0, 0.45), 0 12px 32px rgba(0, 0, 0, 0.5)",
      shadowLg:
        "0 4px 8px rgba(0, 0, 0, 0.5), 0 20px 48px rgba(0, 0, 0, 0.6)",
      shadowPressed: "inset 0 1px 2px rgba(0, 0, 0, 0.5)",
      blur: "12px",
      glow: "0 0 0 4px rgba(157, 123, 255, 0.22)",
      focusRing: `3px solid ${REF.violet}`,
      focusRingOffset: "2px",
    },
    extra: BENTO_EXTRA_DARK,
  },
})
