import type { ThemeDefinition } from "../types"

// Refs: Bloomberg, Drudge Report, brutalist-web.design. AAA contrast 19.8:1 /
// 18.2:1. shadow:none; single hard 2px offset only on press (vs neubrutalism).
// Clashing accent (red) is a FILL with dark text, never red type on white.
export const brutalism: ThemeDefinition = {
  name: "brutalism",
  label: "Brutalism",
  light: {
    "--bg-base": "#ffffff",
    "--bg-subtle": "#fafaf7",
    "--bg-component": "#ffffff",
    "--bg-component-hover": "#ececec",
    "--fg-base": "#0a0a0a",
    "--fg-muted": "#3d3d3d",
    "--fg-subtle": "#5c5c5c",
    "--border-base": "#0a0a0a",
    "--border-strong": "#000000",
    "--bg-interactive": "#1f45ff",
    "--fg-interactive": "#1f45ff",
    "--fg-on-color": "#ffffff",
    "--background": "#ffffff",
    "--surface": "#fafaf7",
    "--primary": "#1f45ff",
    "--secondary": "#ff2e00",
    "--text": "#0a0a0a",
    "--border": "#0a0a0a",
    "--radius": "0px",
    "--border-width": "2px",
    "--shadow": "none",
    "--shadow-pressed": "2px 2px 0 0 #000000",
    "--blur": "0",
    "--glow": "none",
    "--opacity-surface": "1",
  },
  dark: {
    "--bg-base": "#0a0a0a",
    "--bg-subtle": "#121212",
    "--bg-component": "#141414",
    "--bg-component-hover": "#1f1f1f",
    "--fg-base": "#f5f5f5",
    "--fg-muted": "#b5b5b5",
    "--fg-subtle": "#8a8a8a",
    "--border-base": "#f5f5f5",
    "--border-strong": "#ffffff",
    "--bg-interactive": "#4d7bff",
    "--fg-interactive": "#4d7bff",
    "--fg-on-color": "#0a0a0a",
    "--background": "#0a0a0a",
    "--surface": "#121212",
    "--primary": "#4d7bff",
    "--secondary": "#ff5c33",
    "--text": "#f5f5f5",
    "--border": "#f5f5f5",
    "--radius": "0px",
    "--border-width": "2px",
    "--shadow": "none",
    "--shadow-pressed": "2px 2px 0 0 #ffffff",
    "--blur": "0",
    "--glow": "none",
    "--opacity-surface": "1",
  },
}
