import { defineTheme } from "../build-tokens"
import { REF } from "../shared/pro-palette"

/** Brutalism — raw high-contrast, zero radius, hard offset shadows. */
export const brutalism = defineTheme({
  name: "brutalism",
  label: "Brutalism",
  hardSurface: true,
  light: {
    palette: {
      canvas: "#FAFAF7",
      surface: REF.white,
      elevated: REF.white,
      field: REF.white,
      text: "#0A0A0A",
      textMuted: "#3D3D3D",
      textSubtle: "#5C5C5C",
      accent: "#1F45FF",
      accentHover: "#1840E8",
      accentFg: "#1F45FF",
      onAccent: REF.white,
      danger: "#FF2E00",
      border: "#0A0A0A",
      borderStrong: "#000000",
      borderStyle: "hard",
      radius: "0px",
      borderWidth: "2px",
      shadow: "3px 3px 0 0 #0A0A0A",
      shadowSm: "2px 2px 0 0 #0A0A0A",
      shadowMd: "3px 3px 0 0 #0A0A0A",
      shadowLg: "4px 4px 0 0 #0A0A0A",
      shadowPressed: "1px 1px 0 0 #0A0A0A",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #1F45FF",
      focusRingOffset: "2px",
      contrastBg: "#0A0A0A",
      contrastFg: REF.white,
      tags: {
        neutral: {
          bg: "#F0F0F0",
          bgHover: "#E4E4E4",
          text: "#0A0A0A",
          border: "#0A0A0A",
          icon: "#3D3D3D",
        },
        red: {
          bg: "#FFE0D8",
          bgHover: "#FFD0C4",
          text: "#0A0A0A",
          border: "#0A0A0A",
          icon: "#FF2E00",
        },
        blue: {
          bg: "#D8E0FF",
          bgHover: "#C4D0FF",
          text: "#0A0A0A",
          border: "#0A0A0A",
          icon: "#1F45FF",
        },
        green: {
          bg: "#D8F0D8",
          bgHover: "#C4E8C4",
          text: "#0A0A0A",
          border: "#0A0A0A",
          icon: "#0A8A4F",
        },
        orange: {
          bg: "#FFE8C8",
          bgHover: "#FFDCB0",
          text: "#0A0A0A",
          border: "#0A0A0A",
          icon: "#B87400",
        },
        purple: {
          bg: "#E8D8FF",
          bgHover: "#DCC4FF",
          text: "#0A0A0A",
          border: "#0A0A0A",
          icon: "#5B1AA6",
        },
      },
    },
  },
  dark: {
    palette: {
      canvas: "#121212",
      surface: "#0A0A0A",
      elevated: "#141414",
      field: "#141414",
      text: "#F5F5F5",
      textMuted: "#B5B5B5",
      textSubtle: "#8A8A8A",
      accent: "#4D7BFF",
      accentHover: "#6A94FF",
      accentFg: "#7AA0FF",
      onAccent: "#0A0A0A",
      danger: "#FF5C33",
      border: "#F5F5F5",
      borderStrong: REF.white,
      borderStyle: "hard",
      radius: "0px",
      borderWidth: "2px",
      shadow: "3px 3px 0 0 #F5F5F5",
      shadowSm: "2px 2px 0 0 #F5F5F5",
      shadowMd: "3px 3px 0 0 #F5F5F5",
      shadowLg: "4px 4px 0 0 #F5F5F5",
      shadowPressed: "1px 1px 0 0 #F5F5F5",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #4D7BFF",
      focusRingOffset: "2px",
      contrastBg: "#F5F5F5",
      contrastFg: "#0A0A0A",
      tags: {
        neutral: {
          bg: "#1A1A1A",
          bgHover: "#242424",
          text: "#F5F5F5",
          border: "#F5F5F5",
          icon: "#B5B5B5",
        },
        red: {
          bg: "#3A1810",
          bgHover: "#482018",
          text: "#FFB8A0",
          border: "#F5F5F5",
          icon: "#FF5C33",
        },
        blue: {
          bg: "#101A3A",
          bgHover: "#182248",
          text: "#A0B8FF",
          border: "#F5F5F5",
          icon: "#4D7BFF",
        },
        green: {
          bg: "#102A18",
          bgHover: "#183420",
          text: "#A0E8B8",
          border: "#F5F5F5",
          icon: "#00FF88",
        },
        orange: {
          bg: "#3A2810",
          bgHover: "#483418",
          text: "#FFD8A0",
          border: "#F5F5F5",
          icon: "#FFB020",
        },
        purple: {
          bg: "#28103A",
          bgHover: "#341848",
          text: "#D8B8FF",
          border: "#F5F5F5",
          icon: "#A24BFF",
        },
      },
    },
  },
})
