import { defineTheme } from "../build-tokens"

export const brutalism = defineTheme({
  name: "brutalism",
  label: "Brutalism",
  hardSurface: true,
  light: {
    palette: {
      canvas: "#f5f5f0",
      surface: "#ffffff",
      elevated: "#ffffff",
      field: "#ffffff",
      text: "#0a0a0a",
      textMuted: "#3d3d3d",
      textSubtle: "#5c5c5c",
      accent: "#1f45ff",
      accentFg: "#1f45ff",
      onAccent: "#ffffff",
      danger: "#ff2e00",
      border: "#0a0a0a",
      borderStrong: "#000000",
      borderStyle: "hard",
      radius: "0px",
      borderWidth: "2px",
      shadow: "3px 3px 0 0 #0a0a0a",
      shadowSm: "2px 2px 0 0 #0a0a0a",
      shadowMd: "3px 3px 0 0 #0a0a0a",
      shadowLg: "4px 4px 0 0 #0a0a0a",
      shadowPressed: "1px 1px 0 0 #0a0a0a",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #1f45ff",
      focusRingOffset: "2px",
      contrastBg: "#0a0a0a",
      contrastFg: "#ffffff",
      tags: {
        neutral: {
          bg: "#f0f0f0",
          bgHover: "#e4e4e4",
          text: "#0a0a0a",
          border: "#0a0a0a",
          icon: "#3d3d3d",
        },
        red: {
          bg: "#ffe0d8",
          bgHover: "#ffd0c4",
          text: "#0a0a0a",
          border: "#0a0a0a",
          icon: "#ff2e00",
        },
        blue: {
          bg: "#d8e0ff",
          bgHover: "#c4d0ff",
          text: "#0a0a0a",
          border: "#0a0a0a",
          icon: "#1f45ff",
        },
        green: {
          bg: "#d8f0d8",
          bgHover: "#c4e8c4",
          text: "#0a0a0a",
          border: "#0a0a0a",
          icon: "#0a8a4f",
        },
        orange: {
          bg: "#ffe8c8",
          bgHover: "#ffdcb0",
          text: "#0a0a0a",
          border: "#0a0a0a",
          icon: "#b87400",
        },
        purple: {
          bg: "#e8d8ff",
          bgHover: "#dcc4ff",
          text: "#0a0a0a",
          border: "#0a0a0a",
          icon: "#5b1aa6",
        },
      },
    },
  },
  dark: {
    palette: {
      canvas: "#0a0a0a",
      surface: "#141414",
      elevated: "#1a1a1a",
      field: "#141414",
      text: "#f5f5f5",
      textMuted: "#b5b5b5",
      textSubtle: "#8a8a8a",
      accent: "#4d7bff",
      accentFg: "#7aa0ff",
      onAccent: "#0a0a0a",
      danger: "#ff5c33",
      border: "#f5f5f5",
      borderStrong: "#ffffff",
      borderStyle: "hard",
      radius: "0px",
      borderWidth: "2px",
      shadow: "3px 3px 0 0 #f5f5f5",
      shadowSm: "2px 2px 0 0 #f5f5f5",
      shadowMd: "3px 3px 0 0 #f5f5f5",
      shadowLg: "4px 4px 0 0 #f5f5f5",
      shadowPressed: "1px 1px 0 0 #f5f5f5",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #4d7bff",
      focusRingOffset: "2px",
      contrastBg: "#f5f5f5",
      contrastFg: "#0a0a0a",
      tags: {
        neutral: {
          bg: "#1a1a1a",
          bgHover: "#242424",
          text: "#f5f5f5",
          border: "#f5f5f5",
          icon: "#b5b5b5",
        },
        red: {
          bg: "#3a1810",
          bgHover: "#482018",
          text: "#ffb8a0",
          border: "#f5f5f5",
          icon: "#ff5c33",
        },
        blue: {
          bg: "#101a3a",
          bgHover: "#182248",
          text: "#a0b8ff",
          border: "#f5f5f5",
          icon: "#4d7bff",
        },
        green: {
          bg: "#102a18",
          bgHover: "#183420",
          text: "#a0e8b8",
          border: "#f5f5f5",
          icon: "#00ff88",
        },
        orange: {
          bg: "#3a2810",
          bgHover: "#483418",
          text: "#ffd8a0",
          border: "#f5f5f5",
          icon: "#ffb020",
        },
        purple: {
          bg: "#28103a",
          bgHover: "#341848",
          text: "#d8b8ff",
          border: "#f5f5f5",
          icon: "#a24bff",
        },
      },
    },
  },
})
