import { defineTheme } from "../build-tokens"

/** Neubrutalism — neobrutalism.dev, hard offset shadows, bold borders. */
export const neubrutalism = defineTheme({
  name: "neubrutalism",
  label: "Neubrutalism",
  hardSurface: true,
  light: {
    palette: {
      canvas: "#FBEFC9",
      surface: "#FFF4D6",
      elevated: "#FFFFFF",
      field: "#FFFFFF",
      text: "#1A1A1A",
      textMuted: "#4A4A4A",
      textSubtle: "#6B6B6B",
      accent: "#FFDC58",
      accentHover: "#FFD030",
      accentFg: "#1A1A1A",
      onAccent: "#1A1A1A",
      danger: "#E8453C",
      dangerHover: "#D13A32",
      onDanger: "#FFFFFF",
      border: "#1A1A1A",
      borderStrong: "#000000",
      borderStyle: "hard",
      radius: "4px",
      borderWidth: "3px",
      shadow: "4px 4px 0 #1A1A1A",
      shadowSm: "3px 3px 0 #1A1A1A",
      shadowMd: "4px 4px 0 #1A1A1A",
      shadowLg: "6px 6px 0 #1A1A1A",
      shadowPressed: "2px 2px 0 #1A1A1A",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #1A1A1A",
      focusRingOffset: "2px",
      tags: {
        blue: {
          bg: "#C8F0FF",
          bgHover: "#A8E4FF",
          text: "#1A1A1A",
          border: "#1A1A1A",
          icon: "#1A1A1A",
        },
        green: {
          bg: "#B8F5C8",
          bgHover: "#9AEDB0",
          text: "#1A1A1A",
          border: "#1A1A1A",
          icon: "#1A1A1A",
        },
        red: {
          bg: "#FFC8C8",
          bgHover: "#FFB0B0",
          text: "#1A1A1A",
          border: "#1A1A1A",
          icon: "#1A1A1A",
        },
        orange: {
          bg: "#FFE4B8",
          bgHover: "#FFD89A",
          text: "#1A1A1A",
          border: "#1A1A1A",
          icon: "#1A1A1A",
        },
        purple: {
          bg: "#E8D4FF",
          bgHover: "#D8BCFF",
          text: "#1A1A1A",
          border: "#1A1A1A",
          icon: "#1A1A1A",
        },
        neutral: {
          bg: "#F0F0E8",
          bgHover: "#E4E4DC",
          text: "#1A1A1A",
          border: "#1A1A1A",
          icon: "#4A4A4A",
        },
      },
    },
  },
  dark: {
    palette: {
      canvas: "#1D1D22",
      surface: "#16161A",
      elevated: "#23232A",
      field: "#23232A",
      text: "#F2F2E8",
      textMuted: "#B5B5AC",
      textSubtle: "#9A9A92",
      accent: "#F2C744",
      accentHover: "#FFD858",
      accentFg: "#C6F050",
      onAccent: "#16161A",
      danger: "#FF6B5C",
      dangerHover: "#FF8578",
      onDanger: "#16161A",
      border: "#E8E8DC",
      borderStrong: "#FFFFFF",
      borderStyle: "hard",
      radius: "4px",
      borderWidth: "3px",
      shadow: "5px 5px 0 #C6F050",
      shadowSm: "3px 3px 0 #C6F050",
      shadowMd: "5px 5px 0 #C6F050",
      shadowLg: "7px 7px 0 #C6F050",
      shadowPressed: "2px 2px 0 #C6F050",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #F2C744",
      focusRingOffset: "2px",
      contrastBg: "#E8E8DC",
      contrastFg: "#16161A",
      tags: {
        blue: {
          bg: "#1A3040",
          bgHover: "#223848",
          text: "#A8E4FF",
          border: "#E8E8DC",
          icon: "#C8F0FF",
        },
        green: {
          bg: "#1A3020",
          bgHover: "#223828",
          text: "#9AEDB0",
          border: "#E8E8DC",
          icon: "#B8F5C8",
        },
        red: {
          bg: "#3A1A1A",
          bgHover: "#482222",
          text: "#FFB0B0",
          border: "#E8E8DC",
          icon: "#FFC8C8",
        },
        orange: {
          bg: "#3A2A10",
          bgHover: "#483418",
          text: "#FFD89A",
          border: "#E8E8DC",
          icon: "#FFE4B8",
        },
        purple: {
          bg: "#2A1A40",
          bgHover: "#342248",
          text: "#D8BCFF",
          border: "#E8E8DC",
          icon: "#E8D4FF",
        },
        neutral: {
          bg: "#2A2A28",
          bgHover: "#343432",
          text: "#E8E8DC",
          border: "#E8E8DC",
          icon: "#B5B5AC",
        },
      },
    },
  },
})
