import { defineTheme } from "../build-tokens"

export const neubrutalism = defineTheme({
  name: "neubrutalism",
  label: "Neubrutalism",
  hardSurface: true,
  light: {
    palette: {
      canvas: "#fff0b8",
      surface: "#fff8dc",
      elevated: "#ffffff",
      field: "#ffffff",
      text: "#1a1a1a",
      textMuted: "#4a4a4a",
      textSubtle: "#525252",
      accent: "#ffdc58",
      accentFg: "#1a1a1a",
      onAccent: "#1a1a1a",
      danger: "#e8453c",
      dangerHover: "#d13a32",
      onDanger: "#ffffff",
      border: "#1a1a1a",
      borderStrong: "#000000",
      borderStyle: "hard",
      radius: "6px",
      borderWidth: "3px",
      shadow: "5px 5px 0 #1a1a1a",
      shadowSm: "3px 3px 0 #1a1a1a",
      shadowMd: "5px 5px 0 #1a1a1a",
      shadowLg: "7px 7px 0 #1a1a1a",
      shadowPressed: "2px 2px 0 #1a1a1a",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #1a1a1a",
      focusRingOffset: "2px",
      tags: {
        blue: {
          bg: "#c8f0ff",
          bgHover: "#a8e4ff",
          text: "#1a1a1a",
          border: "#1a1a1a",
          icon: "#1a1a1a",
        },
        green: {
          bg: "#b8f5c8",
          bgHover: "#9aedb0",
          text: "#1a1a1a",
          border: "#1a1a1a",
          icon: "#1a1a1a",
        },
        red: {
          bg: "#ffc8c8",
          bgHover: "#ffb0b0",
          text: "#1a1a1a",
          border: "#1a1a1a",
          icon: "#1a1a1a",
        },
        orange: {
          bg: "#ffe4b8",
          bgHover: "#ffd89a",
          text: "#1a1a1a",
          border: "#1a1a1a",
          icon: "#1a1a1a",
        },
        purple: {
          bg: "#e8d4ff",
          bgHover: "#d8bcff",
          text: "#1a1a1a",
          border: "#1a1a1a",
          icon: "#1a1a1a",
        },
        neutral: {
          bg: "#f0f0e8",
          bgHover: "#e4e4dc",
          text: "#1a1a1a",
          border: "#1a1a1a",
          icon: "#4a4a4a",
        },
      },
    },
  },
  dark: {
    palette: {
      canvas: "#16161a",
      surface: "#1d1d22",
      elevated: "#23232a",
      field: "#23232a",
      text: "#f2f2e8",
      textMuted: "#b5b5ac",
      textSubtle: "#9a9a92",
      accent: "#f2c744",
      accentFg: "#c6f050",
      onAccent: "#16161a",
      danger: "#ff6b5c",
      dangerHover: "#ff8578",
      onDanger: "#16161a",
      border: "#e8e8dc",
      borderStrong: "#ffffff",
      borderStyle: "hard",
      radius: "6px",
      borderWidth: "3px",
      shadow: "5px 5px 0 #c6f050",
      shadowSm: "3px 3px 0 #c6f050",
      shadowMd: "5px 5px 0 #c6f050",
      shadowLg: "7px 7px 0 #c6f050",
      shadowPressed: "2px 2px 0 #c6f050",
      blur: "0",
      glow: "none",
      focusRing: "3px solid #f2c744",
      focusRingOffset: "2px",
      contrastBg: "#e8e8dc",
      contrastFg: "#16161a",
      tags: {
        blue: {
          bg: "#1a3040",
          bgHover: "#223848",
          text: "#a8e4ff",
          border: "#e8e8dc",
          icon: "#c8f0ff",
        },
        green: {
          bg: "#1a3020",
          bgHover: "#223828",
          text: "#9aedb0",
          border: "#e8e8dc",
          icon: "#b8f5c8",
        },
        red: {
          bg: "#3a1a1a",
          bgHover: "#482222",
          text: "#ffb0b0",
          border: "#e8e8dc",
          icon: "#ffc8c8",
        },
        orange: {
          bg: "#3a2a10",
          bgHover: "#483418",
          text: "#ffd89a",
          border: "#e8e8dc",
          icon: "#ffe4b8",
        },
        purple: {
          bg: "#2a1a40",
          bgHover: "#342248",
          text: "#d8bcff",
          border: "#e8e8dc",
          icon: "#e8d4ff",
        },
        neutral: {
          bg: "#2a2a28",
          bgHover: "#343432",
          text: "#e8e8dc",
          border: "#e8e8dc",
          icon: "#b5b5ac",
        },
      },
    },
  },
})
