import type { ThemeDefinition } from "../types"

// Refs: neobrutalism.dev, NN/g, shadcn.io. Hard offset shadow, 3px border.
// Dark fix: black offset invisible on near-black -> lime-near-white offset
// (#C6F050, 13.73:1) + off-white border. Fills carry dark text only.
export const neubrutalism: ThemeDefinition = {
  name: "neubrutalism",
  label: "Neubrutalism",
  light: {
    "--bg-base": "#fff4d6",
    "--bg-subtle": "#fbefc9",
    "--bg-component": "#ffffff",
    "--bg-component-hover": "#fff9e6",
    "--fg-base": "#1a1a1a",
    "--fg-muted": "#4a4a4a",
    "--fg-subtle": "#6b6b6b",
    "--border-base": "#1a1a1a",
    "--border-strong": "#000000",
    "--bg-interactive": "#ffdc58",
    "--fg-interactive": "#1a1a1a",
    "--fg-on-color": "#1a1a1a",
    "--background": "#fff4d6",
    "--surface": "#ffffff",
    "--primary": "#ffdc58",
    "--secondary": "#7fd8e8",
    "--text": "#1a1a1a",
    "--border": "#1a1a1a",
    "--radius": "4px",
    "--border-width": "3px",
    "--shadow": "4px 4px 0 #1a1a1a",
    "--shadow-pressed": "2px 2px 0 #1a1a1a",
    "--blur": "0",
    "--glow": "none",
    "--opacity-surface": "1",
  },
  dark: {
    "--bg-base": "#16161a",
    "--bg-subtle": "#1d1d22",
    "--bg-component": "#23232a",
    "--bg-component-hover": "#2d2d35",
    "--fg-base": "#f2f2e8",
    "--fg-muted": "#b5b5ac",
    "--fg-subtle": "#8a8a82",
    "--border-base": "#e8e8dc",
    "--border-strong": "#ffffff",
    "--bg-interactive": "#f2c744",
    "--fg-interactive": "#16161a",
    "--fg-on-color": "#16161a",
    "--background": "#16161a",
    "--surface": "#23232a",
    "--primary": "#f2c744",
    "--secondary": "#5fc8dc",
    "--text": "#f2f2e8",
    "--border": "#e8e8dc",
    "--radius": "4px",
    "--border-width": "3px",
    "--shadow": "4px 4px 0 #c6f050",
    "--shadow-pressed": "2px 2px 0 #c6f050",
    "--blur": "0",
    "--glow": "0 0 0 transparent",
    "--opacity-surface": "1",
  },
}
